name: go-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  go-test:
    name: go-test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ["1.13.x", "1.14.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go }}
      - run: |
          go test -v .
